phraseapp:
  access_token: 61c99574e0b603cfa4398308e2a002bbb952b4f8d4452a243be28da5ab0a9856
  file_format: xml
  project_id: 6de0f32a207690893cb7a61f771aed26
  pull:
    targets:
      - file: ./sdk/src/main/res/values/strings.xml
        params: { locale_id: e1cf8ce0c9fa4ccb2af48029e88a6a96 }
      - file: ./sdk/src/main/res/values-es/strings.xml
        params: { locale_id: 277a19f73fc78ce392b530bf85740793 }
      - file: ./sdk/src/main/res/values-pt/strings.xml
        params: { locale_id: 4238d11aaae7c9c96c03542120ce0c61 }
      - file: ./sdk/src/main/res/values-ru/strings.xml
        params: { locale_id: 435f2d614bc1aa18eb10c9314c935631 }
      - file: ./sdk/src/main/res/values-tr/strings.xml
        params: { locale_id: e474cafb99ed89a8931fb3c200071071 }
  push:
    sources:
      - file: ./sdk/src/main/res/values/strings.xml
        params: { locale_id: e1cf8ce0c9fa4ccb2af48029e88a6a96 }
