apply plugin: 'binary-compatibility-validator'
apply plugin: 'io.github.gradle-nexus.publish-plugin'


buildscript {

    ext {
        sdkVersion = 35
        buildTools = "35.0.0"
        appVersionName = "1.0.0"
        appVersionCode = 102507031
        ext.kotlinVersion = "2.1.21"
    }

    repositories {
        google()
        maven { url "https://www.jitpack.io" }
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.21"
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-appdistribution-gradle:5.1.1'
        classpath 'org.jetbrains.kotlinx:binary-compatibility-validator:0.5.0'
        classpath 'io.github.gradle-nexus:publish-plugin:1.1.0'
        classpath("org.jreleaser:org.jreleaser.gradle.plugin:1.19.0")
    }
}

allprojects {
    repositories {
        google()
        maven { url "https://www.jitpack.io" }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apiValidation {
    ignoredPackages += [
            'com/jivosite/sdk/support/binding',
    ]

    ignoredProjects += [
            'app',
    ]
}
